// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RunModel
List RunModel(NumericVector theta, NumericVector tx_pars, int runtime, double stepsize, NumericVector user_tx_times, NumericVector user_cov_weight, double time_extract_states, NumericMatrix init_female_states, NumericMatrix init_male_states);
RcppExport SEXP _SchistoTransmissionModel_RunModel(SEXP thetaSEXP, SEXP tx_parsSEXP, SEXP runtimeSEXP, SEXP stepsizeSEXP, SEXP user_tx_timesSEXP, SEXP user_cov_weightSEXP, SEXP time_extract_statesSEXP, SEXP init_female_statesSEXP, SEXP init_male_statesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx_pars(tx_parsSEXP);
    Rcpp::traits::input_parameter< int >::type runtime(runtimeSEXP);
    Rcpp::traits::input_parameter< double >::type stepsize(stepsizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type user_tx_times(user_tx_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type user_cov_weight(user_cov_weightSEXP);
    Rcpp::traits::input_parameter< double >::type time_extract_states(time_extract_statesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_female_states(init_female_statesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_male_states(init_male_statesSEXP);
    rcpp_result_gen = Rcpp::wrap(RunModel(theta, tx_pars, runtime, stepsize, user_tx_times, user_cov_weight, time_extract_states, init_female_states, init_male_states));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SchistoTransmissionModel_RunModel", (DL_FUNC) &_SchistoTransmissionModel_RunModel, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_SchistoTransmissionModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
