# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModel <- function(theta, tx_pars, runtime, stepsize, user_tx_times, user_cov_weight) {
    .Call(`_SchistoTransmissionModel_RunModel`, theta, tx_pars, runtime, stepsize, user_tx_times, user_cov_weight)
}

