# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_SchistoTransmissionModel_rcpp_hello_world`)
}

RunModel <- function(theta, runtime, alltimes, tx_pars, tx_times, coverage_data) {
    .Call(`_SchistoTransmissionModel_RunModel`, theta, runtime, alltimes, tx_pars, tx_times, coverage_data)
}

